const tablero_lista = [
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 2,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: -3,
        r: 0,
        s: 3,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 1,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: -3,
        r: 1,
        s: 2,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 1,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: -3,
        r: 2,
        s: 1,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 2,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: -3,
        r: 3,
        s: 0,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 1,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: -2,
        r: -1,
        s: 3,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 2,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: -2,
        r: 0,
        s: 2,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 1,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: -2,
        r: 1,
        s: 1,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 1,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: -2,
        r: 2,
        s: 0,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 1,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: -2,
        r: 3,
        s: -1,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 1,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: -3,
        r: 3,
        s: 0,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 1,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: -1,
        r: -1,
        s: 2,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 2,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: -1,
        r: 0,
        s: 1,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 1,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: -1,
        r: 1,
        s: 0,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 1,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: -1,
        r: 2,
        s: -1,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 1,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: -1,
        r: 3,
        s: -2,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 2,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: 0,
        r: -3,
        s: 3,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 1,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: 0,
        r: -2,
        s: 2,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 1,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: 0,
        r: -1,
        s: 1,
    },
    
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 3,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: 0,
        r: 0,
        s: 0,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 2,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: 0,
        r: 1,
        s: -1,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 2,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: 0,
        r: 2,
        s: -2,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 2,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: 0,
        r: 3,
        s: -3,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 1,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: 1,
        r: -3,
        s: 2,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 1,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: 1,
        r: -2,
        s: 1,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 2,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: 1,
        r: -1,
        s: 0,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 1,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: 1,
        r: 0,
        s: -1,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 1,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: 1,
        r: 1,
        s: -2,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 1,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: 1,
        r: 2,
        s: -3,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 1,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: 2,
        r: -3,
        s: 1,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 2,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: 2,
        r: -2,
        s: 0,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 1,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: 2,
        r: -1,
        s: -1,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 1,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: 2,
        r: 0,
        s: -2,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 1,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: 2,
        r: 1,
        s: -3,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 2,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: 3,
        r: -3,
        s: 0,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 1,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: 3,
        r: -2,
        s: -1,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 1,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: 3,
        r: -1,
        s: -2,
    },
    {
        id_partida: 1,
        id_dueno: 0,
        color: 'purple',
        valor_produccion: 2,
        tipo_ficha: 'None',
        activacion_ficha: false,
        tropas: 0,
        q: 3,
        r: 0,
        s: -3,
    },
];
 export default tablero_lista